# Generated by Django 6.0.2 on 2026-02-19 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='tasks_manag_due_dat_f389be_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_reminder_sent'], name='tasks_manag_due_rem_7d08ba_idx'),
        ),
    ]
